services:
  db:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db



volumes:
  pgdata: